defmodule SportsCoachBookingsWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :sports_coach_bookings

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  #
  # The staff session is scoped to the configured base domain so a single login
  # works across every `{slug}.<base_domain>` tenant. The customer portal cookie
  # (WP-02) is host-only; see docs/rfcs/20260928-tenancy-session-cookie.md.
  @session_options [
    store: :cookie,
    key: "_sports_coach_bookings_key",
    signing_salt:
      Application.compile_env(:sports_coach_bookings, :session_signing_salt, "MOSH6PiA"),
    same_site: "Lax",
    http_only: true,
    secure: Application.compile_env(:sports_coach_bookings, :session_secure, false),
    domain: Application.compile_env(:sports_coach_bookings, :session_domain, nil)
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :sports_coach_bookings,
    gzip: not code_reloading?,
    only: SportsCoachBookingsWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :sports_coach_bookings
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library(),
    body_reader: {SportsCoachBookingsWeb.Plugs.CachedBodyReader, :read_body, []}

  plug Plug.MethodOverride
  plug Plug.Head
  plug SportsCoachBookingsWeb.Plugs.SecurityHeaders
  plug Plug.Session, @session_options
  plug SportsCoachBookingsWeb.Router
end
