import Config

# Configure your database
#
# The application connects as a NON-superuser role (scb_app). This is required
# for Row Level Security to be enforced: superusers and BYPASSRLS roles bypass
# RLS policies even with FORCE ROW LEVEL SECURITY.
config :sports_coach_bookings, SportsCoachBookings.Repo,
  username: "scb_app",
  password: "scb_app",
  hostname: "localhost",
  port: 5432,
  database: System.get_env("DEV_DB_NAME", "sports_coach_bookings_dev"),
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# Base domain used to resolve tenants from the Host header in development.
config :sports_coach_bookings, :base_domain, "localhost"

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :sports_coach_bookings, SportsCoachBookingsWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "2wfOZqE5iHwqiCDfdsOkkd5RJfQAySQZFc41GcuowJ59YF4zL1ObWVwNYTfB5Z0Y",
  watchers: [
    esbuild:
      {Esbuild, :install_and_run, [:sports_coach_bookings, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:sports_coach_bookings, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :sports_coach_bookings, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Links in dev emails must point at the local tenant host (e.g. demo.localhost:4000).
config :sports_coach_bookings, :notifications_url_scheme, "http"
config :sports_coach_bookings, :notifications_url_port, System.get_env("PORT", "4000")

# Staff accounts are platform-wide; their email links open the platform host's admin app.
config :sports_coach_bookings,
       :notifications_app_url,
       "http://localhost:#{System.get_env("PORT", "4000")}"

# Without Stripe credentials, use the in-memory Fake provider so checkout works
# locally (and in the browser e2e suite, which simulates the provider webhook).
# Set STRIPE_SECRET_KEY to exercise the real Stripe adapter in development.
unless System.get_env("STRIPE_SECRET_KEY") do
  config :sports_coach_bookings,
         :payments_provider,
         SportsCoachBookings.Payments.Providers.Fake
end

# The browser e2e suite signs up many accounts from one IP, so it runs with
# RATE_LIMITING=off. Limiter behaviour is covered by test/security/rate_limit_test.exs.
config :sports_coach_bookings,
       :rate_limiting_enabled,
       System.get_env("RATE_LIMITING") != "off"
