import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :sports_coach_bookings, SportsCoachBookingsWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :sports_coach_bookings, SportsCoachBookingsWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: [
      # Platform health checks hit the machine directly over the private
      # network without an X-Forwarded-Proto header; don't redirect them.
      paths: ["/health", "/health/ready"],
      hosts: ["localhost", "127.0.0.1"]
    ]
  ]

# Staff session cookie spans every tenant subdomain in production. The customer
# portal cookie (WP-02) is host-only.
config :sports_coach_bookings, :session_domain, ".sportscoachbookings.com"

# HTTPS-only cookies in production (WP-19).
config :sports_coach_bookings, :session_secure, true

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Chrome-backed waiver rendering preserves Unicode, tenant colours/fonts, and
# logos. The runtime image installs Chromium and Noto's broad Unicode fonts.
config :sports_coach_bookings,
       :waiver_pdf_renderer,
       SportsCoachBookings.Waivers.PdfRenderer.Browser

config :sports_coach_bookings, ChromicPDF,
  chrome_executable: "/usr/bin/chromium",
  no_sandbox: true,
  disable_scripts: true,
  session_pool: [size: 1, timeout: 15_000, checkout_timeout: 15_000]

# WP-20: one JSON object per line, including request_id/tenant_id, so the Fly
# log drain and error trackers can index fields without a parsing pipeline.
config :logger, :default_formatter, format: {SportsCoachBookings.Logger.Formatter, :format}

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
